### PR TITLE
Add CIP 3, concerning Setup Input

### PR DESCRIPTION
**Pull request by augustoteixeira**
This PR adds a CIP 3 describing the Setup Input which will enter the machine during deployment to inform it about the application's address.

### CODE REVIEW

**Comment by felipeargento** [comment]
@augustoteixeira I tried suggesting a change (throught -> through) but accidentally committed it.  It seems like there is already a cip-3 in main though, so maybe we should add some CI requirements here :)

Also think that we should invite @fcecin to review this!

**Comment by felipeargento** [comment]
> oul

Yeah, I think this is the first improvement to this. Instead of it being an empty input we could allow for an arbitrary payload that can contain as much setup information as the dapp requires.

**Comment by fcecin** [comment]
Hi guys!

1. Some CI would be nice. It's not urgent; we can LARP the role of the CI with manual commits for a while. It's not like this process is mediating multiple implementors yet, so it's fine. It's actually good that we pilot this manually before we can extract what we actually need from the CI (because the CIP process itself might change because of being put to some first use). Let's make some mistakes first.

2. The "discussions-to:" header is not optional. Someone needs to add a post on the Cartesi Governance Forum with "Hey, we are creating CIP-3, it's self-explanatory, go read it." at least, and then use the URL of that post in the "discussions-to:" header. This would ideally be fixed on the pull request code before it is committed, but, again, it's fine, if the champion(s) of the CIP can just patch it up on main at some point it's good.

3. Remember that for this CIP to move to Final status, it will need implementation released on the public Cartesi repo.

That's it. Not too bureaucratic, is it?

**Review by fcecin — APPROVED** [review]
This fixes a typo.

There's still the missing discussions-to: header. This can be fixed later by whoever is going to write the post on the governance forum.

**Comment by felipeargento** [comment]
Created a PR adding the discussion-to header and the governance post :)

**Pull request closed without merging**
